---
# file: roles/rpi/tasks/geth.yml

- name: Add the geth system group
  group:
    name: geth
    system: yes

- name: Add the geth system user
  user:
    name: geth
    create_home: no
    shell: /usr/bin/false
    system: yes
    group: geth

- name: Download Geth for ARM64
  get_url:
    url: https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-arm64-{{ geth_version }}.tar.gz
    dest: /tmp/geth-alltools-linux-{{ geth_version }}.tar.gz
    checksum: md5:{{ geth_md5 }}
  when: ansible_architecture == "aarch64"

- name: Download Geth for ARMv7
  get_url:
    url: https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-arm7-{{ geth_version }}.tar.gz
    dest: /tmp/geth-alltools-linux-{{ geth_version }}.tar.gz
    checksum: md5:{{ geth_md5 }}
  when: ansible_architecture == "armv7l"

- name: Extract Geth tarball
  unarchive:
    src: /tmp/geth-alltools-linux-{{ geth_version }}.tar.gz
    dest: /tmp
    owner: geth
    group: geth
    remote_src: yes

- name: Move Geth binaries to PATH
  copy:
    src: '/tmp/geth-alltools-linux-arm64-{{ geth_version }}/{{ item.src }}'
    dest: '/usr/local/bin/{{ item.path }}'
    mode: 0755
    remote_src: yes
  with_items:
    - { src: 'geth', path: 'geth' }

- name: Delete unused files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - "/tmp/geth-alltools-linux-{{ geth_version }}"
    - "/tmp/geth-alltools-linux-{{ geth_version }}.tar.gz"

- name: Create data directory for geth
  file:
    path: /var/lib/geth
    owner: geth
    group: geth
    state: directory
    mode: '0755'

- name: Copy systemd file for geth service
  copy:
    src: geth.service
    dest: /lib/systemd/system/geth.service
    owner: root
    group: root
    mode: '0644'

- name: Install pcscd
  package:
    update_cache: yes
    name: pcscd
    state: present

- name: Start Geth service
  service:
    name: geth
    enabled: yes
