---
# file: roles/rpi/tasks/geth.yml

- name: Add the geth system group
  group:
    name: geth
    system: yes

- name: Add the geth system user
  user:
    name: geth
    create_home: no
    shell: /usr/bin/false
    system: yes
    group: geth

- name: Download Geth for ARM64
  ansible.builtin.unarchive:
    src: https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-arm64-{{ geth_version }}.tar.gz
    dest: /usr/local/bin
    owner: geth
    group: geth
    remote_src: yes
  when: ansible_architecture == "aarch64"

- name: Create data directory for geth
  file:
    path: /var/lib/geth
    owner: geth
    group: geth
    state: directory
    mode: '0755'

- name: Copy systemd file for geth service
  ansible.builtin.copy:
    src: geth.service
    dest: /lib/systemd/system/geth.service
    owner: root
    group: root
    mode: '0644'

- name: Enable Geth service at boot
  ansible.builtin.service:
    name: geth
    enabled: true

- name: Start Geth service
  ansible.builtin.service:
    name: geth
    state: restarted
