---
# file: roles/rpi/tasks/geth.yml

- name: Download Go for ARMv6
  get_url:
    url: https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-armv6l.tar.gz
    dest: /tmp/go1.9.2.linux-armv6l.tar.gz
    checksum: sha256:8a6758c8d390e28ef2bcea511f62dcb43056f38c1addc06a8bc996741987e7bb
  tags: go

- name: Extract Go tarball
  unarchive:
    src: /tmp/go1.9.2.linux-armv6l.tar.gz
    dest: /usr/local
    remote_src: yes
  tags: go

- name: Add Go binaries to the PATH
  file:
    src: '/usr/local/go/bin/{{ item.src }}'
    path: '/usr/local/bin/{{ item.path }}'
    state: link
    force: yes
  with_items:
    - { src: 'go', path: 'go' }
    - { src: 'godoc', path: 'godoc' }
    - { src: 'gofmt', path: 'gofmt' }
  tags: go

- name: Download Geth for ARMv7
  get_url:
    url: https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-arm7-{{ geth_version }}.tar.gz
    dest: /tmp/geth-alltools-linux-arm7-{{ geth_version }}.tar.gz
    checksum: md5:{{ geth_md5 }}

- name: Extract Geth tarball
  unarchive:
    src: /tmp/geth-alltools-linux-arm7-{{ geth_version }}.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move Geth binaries to PATH
  copy:
    src: '/tmp/geth-alltools-linux-arm7-{{ geth_version }}/{{ item.src }}'
    dest: '/usr/local/bin/{{ item.path }}'
    mode: 0755
    remote_src: yes
  with_items:
    - { src: 'geth', path: 'geth' }

- name: Delete unused files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - "/tmp/geth-alltools-linux-arm7-{{ geth_version }}"
    - "/tmp/geth-alltools-linux-arm7-{{ geth_version }}.tar.gz"

- name: Add the geth system group
  group:
    name: geth
    system: yes

- name: Add the geth system user
  user:
    name: geth
    create_home: no
    shell: /usr/bin/false
    system: yes
    group: geth

- name: Create data directory for geth
  file:
    path: /var/lib/geth
    owner: geth
    group: geth
    state: directory
    mode: '0755'

- name: Copy systemd file for geth service
  copy:
    src: geth.service
    dest: /lib/systemd/system/geth.service
    owner: root
    group: root
    mode: '0644'

- name: Start Geth service
  service:
    name: geth
    enabled: yes
