---
# file: roles/rpi/tasks/go.yml

- name: "[{{ ansible_architecture }}] Download and extract Go tarball"
  ansible.builtin.unarchive:
    src: https://go.dev/dl/go1.18.2.linux-arm64.tar.gz
    dest: /usr/local
    remote_src: yes
  when: ansible_architecture == 'aarch64'

- name: Copy Go binaries to PATH
  ansible.builtin.file:
    src: '/usr/local/go/bin/{{ item }}'
    dest: '/usr/local/bin/{{ item }}'
    state: link
  loop:
    - go
    - gofmt
