---
# file: roles/rpi/tasks/prometheus.yml

- name: Download Grafana for ARMv7
  get_url:
    url: https://dl.grafana.com/oss/release/grafana-6.7.3.linux-armv7.tar.gz
    dest: /tmp/grafana-6.7.3.linux-armv7.tar.gz
    checksum: sha256:2f86a43f6946e085b1bf92f91a836a66574a39cf8712a444e1646ce0366cb54f

- name: Extract Grafana tarball
  unarchive:
    src: /tmp/grafana-6.7.3.linux-armv7.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move Grafana binaries to PATH
  copy:
    src: '/tmp/grafana-6.7.3/bin/{{ item }}'
    dest: '/usr/local/bin/{{ item }}'
    mode: 0755
    remote_src: yes
  with_items:
    - 'grafana-cli'
    - 'grafana-server'

    #- name: Copy Grafana service file
    #  template:
    #    src: templates/prometheus.service.j2
    #    dest: /lib/systemd/system/prometheus.service
    #    #validate: systemd-analyze verify %s
    #    owner: root
    #    group: root
    #    mode: '0644'

- name: Create a settings directory if it does not exist
  file:
    path: /etc/grafana
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Grafana configuration file
  template:
    src: templates/grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: '0644'

    #- name: Delete unused files
    #  file:
    #    path: '{{ item }}'
    #    state: absent
    #  with_items:
    #    - '/tmp/prometheus-2.17.2.linux-armv7.tar.gz'
