---
# file: roles/rpi/tasks/main.yml

- name: Remove pi user
  user:
    name: pi
    state: absent
    remove: yes
    force: yes
  tags:
    - rpi
    - user

- name: Copy systemd file for fan control
  copy:
    src: 50-rpi-fan.rules
    dest: /etc/udev/rules.d/50-rpi-fan.rules
    owner: root
    group: root
    mode: '0640'
  tags: rpi

- name: Reload udev rules
  shell: udevadm control --reload-rules && udevadm trigger
  tags: rpi

- name: Remove pi group
  group:
    name: pi
    state: absent
  tags:
    - rpi
    - user

- import_tasks: prometheus.yml
  tags: prometheus

- import_tasks: grafana.yml
  tags: grafana

- import_tasks: go.yml
  tags: go

- import_tasks: snap.yml
  tags: snap
