---
# file: roles/rpi/tasks/main.yml

- name: Copy udev rules for Raspberry Pi fan control
  ansible.builtin.copy:
    src: "{{  item }}"
    dest: /etc/udev/rules.d/
    owner: root
    group: root
    mode: '0640'
  loop:
    - 50-rpi-fan.rules
    - 51-cpu-governor.rules
  tags: fan

- name: Reload udev rules
  shell: udevadm control --reload-rules && udevadm trigger
  tags: fan

- import_tasks: packages.yml
  tags: rpi
