---
# file: roles/rpi/tasks/main.yml
- name: Copy systemd file for fan control
  copy:
    src: 50-rpi-fan.rules
    dest: /etc/udev/rules.d/50-rpi-fan.rules
    owner: root
    group: root
    mode: '0640'
  tags: fan

- name: Reload udev rules
  shell: udevadm control --reload-rules && udevadm trigger
  tags: fan

- import_tasks: packages.yml
  tags: rpi
