---

- name: Enable SSH on boot
  file:
    path: /boot/ssh
    state: touch
  tags: ssh

- name: Rotate screen 270 degrees
  lineinfile:
    path: /boot/config.txt
    state: present
    line: 'display_rotate=3'

- name: Remove pi user
  user:
    name: pi
    state: absent
    remove: yes
  tags: user

- name: Rename hostname
  hostname:
    name: spoon
  tags: hostname

- include: geth.yml
  tags: geth

