---
# file: roles/rpi/tasks/main.yml

- name: Enable SSH on boot
  file:
    path: /boot/ssh
    state: touch
  tags:
    - rpi
    - ssh

- name: Rename hostname
  hostname:
    name: spoon
  tags:
    - rpi
    - hostname

- name: Remove pi user
  user:
    name: pi
    state: absent
    remove: yes
  tags:
    - rpi
    - user

- name: Rotate screen 270 degrees
  lineinfile:
    path: /boot/config.txt
    state: present
    line: 'display_rotate=3'
  tags: never

- import_tasks: geth.yml
  tags: geth

- import_tasks: terraform.yml
  tags: never

- import_tasks: node-exporter.yml
  tags: node-exporter
