---
# file: roles/rpi/tasks/node-exporter.yml

- name: Download Prometheus' node-exporter for ARM64
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-arm64.tar.gz
    dest: /tmp/node_exporter-1.0.1.linux-arm64.tar.gz
    checksum: sha256:017514906922fcc4b7d727655690787faed0562bc7a17aa9f72b0651cb1b47fb

- name: Extract node-exporter tarball
  unarchive:
    src: /tmp/node_exporter-1.0.1.linux-arm64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move node-exporter binary to PATH
  copy:
    src: '/tmp/node_exporter-1.0.1.linux-arm64/node_exporter'
    dest: '/usr/local/bin/node_exporter'
    mode: 0755
    remote_src: yes

- name: Delete unused files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/tmp/node_exporter-1.0.1.linux-arm64'
    - '/tmp/node_exporter-1.0.1.linux-arm64.tar.gz'

- name: Copy systemd file for node-exporter service
  template:
    src: templates/node-exporter.service.j2
    dest: /lib/systemd/system/node-exporter.service
    owner: root
    group: root
    mode: '0644'

- name: Copy node-exporter settings file
  template:
    src: templates/node-exporter.conf.j2
    dest: /etc/default/node-exporter.conf
    owner: root
    group: root
    mode: '0644'

- name: Start node-exporter service
  service:
    name: node-exporter
    state: restarted
    daemon_reload: yes

- name: Enable node-exporter service to start on boot
  service:
    name: node-exporter
    enabled: yes
