---
# file: roles/rpi/tasks/prometheus.yml

- name: Download Prometheus for ARMv7
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.17.2/prometheus-2.17.2.linux-armv7.tar.gz
    dest: /tmp/prometheus-2.17.2.linux-armv7.tar.gz
    checksum: sha256:ef288c8182c07e662378e1a66d10ff04dc9d8a9f99a747a5ed095e6e4cf95065

- name: Extract Prometheus tarball
  unarchive:
    src: /tmp/prometheus-2.17.2.linux-armv7.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move Prometheus binaries to PATH
  copy:
    src: '/tmp/prometheus-2.17.2.linux-armv7/{{ item }}'
    dest: '/usr/local/bin/{{ item }}'
    mode: 0755
    remote_src: yes
  with_items:
    - 'prometheus'

- name: Copy Prometheus service file
  template:
    src: templates/prometheus.service.j2
    dest: /lib/systemd/system/prometheus.service
    #validate: systemd-analyze verify %s
    owner: root
    group: root
    mode: '0644'

- name: Create a directory if it does not exist
  file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Prometheus configuration file
  template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'

- name: Delete unused files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/tmp/prometheus-2.17.2.linux-armv7.tar.gz'
    - '/tmp/prometheus-2.17.2.linux-armv7'
