---
# file: roles/geth/tasks/geth.yml

- name: Add the geth system group
  group:
    name: geth
    system: yes

- name: Add the geth system user
  user:
    name: geth
    create_home: no
    shell: /usr/bin/false
    system: yes
    group: geth

- name: "[{{ ansible_architecture }}] Download Geth"
  ansible.builtin.unarchive:
    src: https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-{{ geth_version }}.tar.gz
    dest: /tmp
    remote_src: yes
  when: ansible_architecture == "x86_64"

- name: "[{{ ansible_architecture }}] Download Geth"
  ansible.builtin.unarchive:
    src: https://gethstore.blob.core.windows.net/builds/geth-linux-arm64-{{ geth_version }}.tar.gz
    dest: /tmp
    remote_src: yes
  when: ansible_architecture == "aarch64"

- name: "[{{ ansible_architecture }}] Copy geth binary"
  ansible.builtin.copy:
    src: /tmp/geth-linux-amd64-{{ geth_version }}/geth
    dest: /usr/local/bin/geth
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
  when: ansible_architecture == "x86_64"

- name: "[{{ ansible_architecture }}] Copy geth binary"
  ansible.builtin.copy:
    src: /tmp/geth-linux-arm64-{{ geth_version }}/geth
    dest: /usr/local/bin/geth
    remote_src: yes
    owner: root
    group: root
    mode: '0755'
  when: ansible_architecture == "aarch64"

- name: Create data directory for geth
  ansible.builtin.file:
    path: /var/lib/geth
    owner: geth
    group: geth
    state: directory
    mode: '0755'

- name: Copy systemd file for geth service
  ansible.builtin.copy:
    src: geth.service
    dest: /lib/systemd/system/geth.service
    owner: root
    group: root
    mode: '0644'

- name: Install pcscd
  ansible.builtin.package:
    update_cache: yes
    name: pcscd
    state: present

- name: Enable Geth service on boot
  ansible.builtin.service:
    name: geth
    enabled: yes

- name: Start Geth service, if not started
  ansible.builtin.service:
    name: geth
    state: started
