---
# file: roles/geth/tasks/geth.yml

- name: Add the geth system group
  group:
    name: geth
    system: yes

- name: Add the geth system user
  user:
    name: geth
    create_home: no
    shell: /usr/bin/false
    system: yes
    group: geth

- name: "[{{ ansible_architecture }}] Download Geth"
  ansible.builtin.unarchive:
    src: https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-{{ geth_version }}.tar.gz
    dest: /tmp
    remote_src: yes
  when: ansible_architecture == 'x86_64'

- name: "[{{ ansible_architecture }}] Move Geth binaries to PATH"
  ansible.builtin.copy:
    src: '/tmp/geth-linux-amd64-{{ geth_version }}/geth'
    dest: '/usr/local/bin/geth'
    mode: 0755
    remote_src: yes
  when: ansible_architecture == 'x86_64'

- name: "[{{ ansible_architecture }}] Download Geth"
  ansible.builtin.unarchive:
    src: https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-arm64-{{ geth_version }}.tar.gz
    dest: /tmp
    remote_src: yes
  when: ansible_architecture == "aarch64"

- name: "[{{ ansible_architecture }}] Move Geth binaries to PATH"
  ansible.builtin.copy:
    src: '/tmp/geth-alltools-linux-arm64-{{ geth_version }}/{{ item }}'
    dest: '/usr/local/bin/{{ item }}'
    mode: 0755
    remote_src: yes
  with_items:
    - "clef"
    - "geth"
  when: ansible_architecture == "aarch64"

- name: Delete unused files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - "/tmp/geth-alltools-linux-{{ geth_version }}"
    - "/tmp/geth-alltools-linux-{{ geth_version }}.tar.gz"

- name: Create data directory for geth
  file:
    path: /var/lib/geth
    owner: geth
    group: geth
    state: directory
    mode: '0755'

- name: Copy systemd file for geth service
  copy:
    src: geth.service
    dest: /lib/systemd/system/geth.service
    owner: root
    group: root
    mode: '0644'

- name: Install pcscd
  package:
    update_cache: yes
    name: pcscd
    state: present

- name: Enable Geth service on boot
  ansible.builtin.service:
    name: geth
    enabled: yes

- name: Start Geth service, if not started
  ansible.builtin.service:
    name: geth
    state: started
