- name: Extract Alertmanager tarball (ARMv6)
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-armv6.tar.gz
    dest: /tmp
    remote_src: yes
    creates: '/tmp/alertmanager-{{ alertmanager_version }}.linux-armv6.tar.gz'
  when: ansible_architecture == "armv6l"

- name: Move Alertmanager binaries to PATH (ARMv6)
  copy:
    src: '/tmp/alertmanager-{{ alertmanager_version }}.linux-armv6/{{ item }}'
    dest: '/usr/local/bin/{{ item }}'
    mode: 0755
    remote_src: yes
  with_items:
    - 'alertmanager'
    - 'amtool'
  when: ansible_architecture == "armv6l"

- name: Create a directory if it does not exist
  file:
    path: /etc/alertmanager
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Alertmanager configuration file
  template:
    src: templates/alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: root
    group: root
    mode: '0644'

- name: Copy Alertmanager service file
  copy:
    src: alertmanager.service
    dest: /lib/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: '0644'

- name: Delete unused files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/tmp/alertmanager-{{ alertmanager_version }}.linux-armv6'
    - '/tmp/alertmanager-{{ alertmanager_version }}.linux-armv6.tar.gz'

- name: Enable Alertmanager service to start on boot
  service:
    name: alertmanager
    enabled: yes

- name: Start Alertmanager service
  service:
    name: alertmanager
    state: restarted
    daemon_reload: yes
