---
# file: roles/prometheus/tasks/blackbox-exporter.yml

- name: "[{{ ansible_architecture }}] Download and extract blackbox-exporter tarball"
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-arm64.tar.gz 
    dest: /tmp
    remote_src: yes
    creates: '/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-arm64.tar.gz'
  when: ansible_architecture == 'aarch64'

- name: Move blackbox-exporter binary to PATH
  ansible.builtin.copy:
    src: '/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-arm64/blackbox_exporter'
    dest: '/usr/local/bin/blackbox_exporter'
    mode: 0755
    remote_src: yes
  when: ansible_architecture == 'aarch64'

- name: Delete unused files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-arm64'
    - '/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-arm64.tar.gz'
  when: ansible_architecture == 'aarch64'

- name: Copy systemd file for blackbox-exporter service
  template:
    src: templates/blackbox-exporter.service.j2
    dest: /lib/systemd/system/blackbox-exporter.service
    owner: root
    group: root
    mode: '0644'

- name: Copy blackbox-exporter settings file
  template:
    src: templates/blackbox.yml.j2
    dest: /etc/default/blackbox.yml
    owner: root
    group: root
    mode: '0644'

- name: Start blackbox-exporter service
  service:
    name: blackbox-exporter
    state: restarted
    daemon_reload: yes

- name: Enable blackbox-exporter service to start on boot
  service:
    name: blackbox-exporter
    enabled: yes
