---
# file: roles/prometheus/tasks/main.yml

- name: Extract Prometheus tarball (ARMv6)
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-armv6.tar.gz
    dest: /tmp
    remote_src: yes
    creates: '/tmp/prometheus-{{ prometheus_version }}.linux-armv6'
  when: ansible_architecture == "armv6l"

- name: Move Prometheus binaries to PATH (ARMv6)
  copy:
    src: '/tmp/prometheus-{{ prometheus_version }}.linux-armv6/{{ item }}'
    dest: '/usr/local/bin/{{ item }}'
    mode: 0755
    remote_src: yes
  with_items:
    - 'prometheus'
  when: ansible_architecture == "armv6l"

- name: Copy Prometheus service file
  template:
    src: templates/prometheus.service.j2
    dest: /lib/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'

- name: Create a directory if it does not exist
  file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Prometheus configuration file
  template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'

- name: Delete unused files
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/tmp/prometheus-{{ prometheus_version }}.linux-armv6.tar.gz'
    - '/tmp/prometheus-{{ prometheus_version }}.linux-armv6'

- name: Enable Prometheus service to start on boot
  service:
    name: prometheus
    enabled: yes

- name: Start Prometheus service
  service:
    name: prometheus
    state: restarted
    daemon_reload: yes
