---
# file: roles/prometheus/tasks/main.yml

- import_tasks: prometheus.yml
  tags: prometheus

- import_tasks: alertmanager.yml
  tags: alertmanager

- import_tasks: node-exporter.yml
  tags: node-exporter

- import_tasks: blackbox-exporter.yml
  tags: blackbox

