---
# file: roles/paixao/tasks/dotfiles.yml

- name: Clone repository
  git:
    repo: 'https://github.com/willianpaixao/dotfiles.git'
    dest: /home/willian/dev/paixao/dotfiles
    version: HEAD
  become: true
  become_user: willian
  tags:
    - dotfiles
    - git

- name: Create symbolic links
  file:
    src: '/home/willian/dev/paixao/dotfiles/{{ item.src }}'
    path: '/home/willian/{{ item.path }}'
    state: link
    force: yes
  become: true
  become_user: willian
  with_items:
          - { src: 'bash_aliases', path: '.bash_aliases' }
          - { src: 'bash_completion', path: '.bash_completion' }
          - { src: 'bash_logout', path: '.bash_logout' }
          - { src: 'bashrc', path: '.bashrc' }
          - { src: 'gitconfig', path: '.gitconfig' }
          - { src: 'tmux.conf', path: '.tmux.conf' }
          - { src: 'vimrc', path: '.vimrc' }
          - { src: 'xinitrc', path: '.xinitrc' }
          - { src: 'Xresources', path: '.Xresources' }
  tags: dotfiles
