---
# file: roles/rpi/tasks/snap.yml

- name: Remove all snaps
  community.general.snap:
    name:
      - lxd
      - core20
      - snapd
    state: absent
  when: ansible_architecture == 'aarch64' and ansible_facts['distribution'] == 'Ubuntu'

- name: Remove snapd package
  apt:
    name: snapd
    state: absent
  when: ansible_architecture == 'aarch64' and ansible_facts['distribution'] == 'Ubuntu'
