---
# file: roles/base/tasks/user.yml

- name: Add willian user
  user:
    name: willian
    shell: /bin/bash
    comment: "Willian Paixao"
    groups: sudo
    append: yes
  tags: user

- name: Add ssh public key willianATatari
  authorized_key:
    user: willian
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  tags: user

- name: Change sudo to without password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo\s'
    line: '%sudo   ALL=(ALL:ALL) NOPASSWD:ALL'
  tags:
    - user
    - never

- name: Change keyboard layout to Swedish
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBLAYOUT="gb"'
    line: 'XKBLAYOUT="se"'
  tags:
    - user
    - never
