repos:
- repo: local
  hooks:
  -   id: ansible-lint
      name: Ansible-lint
      description: This hook runs ansible-lint.
      entry: ansible-lint
      language: python
      files: \.(yaml|yml)$
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.1.1
  hooks:
  -   id: trailing-whitespace
  -   id: check-merge-conflict
