---
# file: site.yml
# version: v1.1

- name: Install base packages
  hosts: all
  tasks:
    - import_role:
        name: base
      tags: base

- name: Install monitoring tools (server)
  hosts: monitoring
  tasks:
    - import_role:
        name: prometheus
      tags: prometheus
    - import_role:
        name: grafana
      tags: grafana

- name: Install monitoring tools (agents)
  hosts: logos,nebuchadnezzar
  tasks:
    - import_role:
        name: prometheus
        tasks_from: node-exporter.yml
  tags: node-exporter
