---
# file: site.yml
# version: v1.1

- name: Install base packages
  hosts: all
  tasks:
  - import_role:
      name: base
    tags: base

- name: Install monitoring tools
  hosts: vigilant
  tasks:
  - import_role:
      name: prometheus
    tags: prometheus
  - import_role:
      name: grafana
    tags: grafana
