---
# file: site.yml
# version: v1.1

- name: Install base packages
  hosts: all
  tasks:
    - import_role:
        name: base

- name: Common Raspberry tasks
  hosts: aarch64
  tasks:
    - import_role:
        name: rpi
  tags: rpi

- name: Install Geth
  hosts: geth
  tasks:
    - import_role:
        name: geth
  tags: geth

- name: Install monitoring agents
  hosts: all
  tasks:
    - import_role:
        name: prometheus
        tasks_from: node-exporter
  tags: node-exporter
