---
# file: site.yml
# version: v1.1

- name: Install base packages
  hosts: all
  tasks:
    - import_role:
        name: base

- name: Common Raspberry tasks
  hosts: aarch64
  tasks:
    - import_role:
        name: rpi

- name: Install monitoring stack
  hosts: all
  tasks:
    - import_role:
        name: prometheus
    - import_role:
        name: grafana

- name: Install Geth
  hosts: geth
  tasks:
    - import_role:
        name: geth
