name: ansible-lint

on: [push, pull_request]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0
      - name: Run ansible-lint
        uses: ansible/ansible-lint@fac2489f3e4ccffa83a40b839770abbf4ab52327 # main
